<a href="https://colab.research.google.com/github/Thilaak123/Phonepe-Pulse-Data-Visualization-and-Exploration/blob/main/Phonepe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import plotly.express as px
import json
import os
os.environ["GIT_PYTHON_REFRESH"] = "quiet"
import git
# !pip install GitPython
from PIL import Image

In [ ]:
gitclone : "https://github.com/PhonePe/pulse.git"

In [ ]:
path1 = "/content/pulse/data/aggregated/transaction/country/india/state/"
agg_trans_list = os.listdir(path1)

columns1 = {'State': [], 'Year': [], 'Quarter': [], 'Transaction_type': [], 'Transaction_count': [],
            'Transaction_amount': []}
for state in agg_trans_list:
    cur_state = path1 + state + "/"
    agg_year_list = os.listdir(cur_state)

    for year in agg_year_list:
        cur_year = cur_state + year + "/"
        agg_file_list = os.listdir(cur_year)

        for file in agg_file_list:
            cur_file = cur_year + file
            data = open(cur_file, 'r')
            A = json.load(data)

            for i in A['data']['transactionData']:
                name = i['name']
                count = i['paymentInstruments'][0]['count']
                amount = i['paymentInstruments'][0]['amount']
                columns1['Transaction_type'].append(name)
                columns1['Transaction_count'].append(count)
                columns1['Transaction_amount'].append(amount)
                columns1['State'].append(state)
                columns1['Year'].append(year)
                columns1['Quarter'].append(int(file.strip('.json')))

df_agg_trans = pd.DataFrame(columns1)

In [ ]:
df_agg_trans.shape

(5034, 6)

In [ ]:
df_agg_trans

,State,Year,Quarter,Transaction_type,Transaction_count,Transaction_amount
0,chandigarh,2018,1,Recharge & bill payments,201262,4.747958e+07
1,chandigarh,2018,1,Peer-to-peer payments,135136,5.279988e+08
2,chandigarh,2018,1,Merchant payments,21431,1.947707e+07
3,chandigarh,2018,1,Financial Services,8473,1.865618e+06
4,chandigarh,2018,1,Others,15593,1.661431e+07
...,...,...,...,...,...,...
5029,delhi,2023,4,Merchant payments,381250463,1.687665e+11
5030,delhi,2023,4,Peer-to-peer payments,185276322,5.881312e+11
5031,delhi,2023,4,Recharge & bill payments,30903762,4.188944e+10
5032,delhi,2023,4,Financial Services,317005,5.013539e+08
5033,delhi,2023,4,Others,403194,3.612766e+08

In [ ]:
path2 = "/content/pulse/data/aggregated/user/country/india/state/"

agg_user_list = os.listdir(path2)

columns2 = {'State': [], 'Year': [], 'Quarter': [], 'Brands': [], 'Count': [],
            'Percentage': []}
for state in agg_user_list:
    cur_state = path2 + state + "/"
    agg_year_list = os.listdir(cur_state)

    for year in agg_year_list:
        cur_year = cur_state + year + "/"
        agg_file_list = os.listdir(cur_year)

        for file in agg_file_list:
            cur_file = cur_year + file
            data = open(cur_file, 'r')
            B = json.load(data)

            try:
                for i in B["data"]["usersByDevice"]:
                    brand_name = i["brand"]
                    counts = i["count"]
                    percents = i["percentage"]
                    columns2["Brands"].append(brand_name)
                    columns2["Count"].append(counts)
                    columns2["Percentage"].append(percents)
                    columns2["State"].append(state)
                    columns2["Year"].append(year)
                    columns2["Quarter"].append(int(file.strip('.json')))
            except:
                pass

df_agg_user = pd.DataFrame(columns2)

In [ ]:
df_agg_user.shape

(6732, 6)

In [ ]:
df_agg_user

           State  Year  Quarter    Brands   Count  Percentage
0     chandigarh  2018        1    Xiaomi   20555    0.238269
1     chandigarh  2018        1   Samsung   17266    0.200144
2     chandigarh  2018        1      Vivo    9360    0.108499
3     chandigarh  2018        1      Oppo    7948    0.092131
4     chandigarh  2018        1     Apple    7552    0.087541
...          ...   ...      ...       ...     ...         ...
6727       delhi  2020        4   OnePlus  256533    0.026317
6728       delhi  2020        4  Motorola  246834    0.025322
6729       delhi  2020        4    Huawei  168898    0.017326
6730       delhi  2020        4    Lenovo  134947    0.013844
6731       delhi  2020        4    Others  827035    0.084842

[6732 rows x 6 columns]

In [ ]:
path3 = "/content/pulse/data/map/transaction/hover/country/india/state/"

map_trans_list = os.listdir(path3)

columns3 = {'State': [], 'Year': [], 'Quarter': [], 'District': [], 'Count': [],
            'Amount': []}

for state in map_trans_list:
    cur_state = path3 + state + "/"
    map_year_list = os.listdir(cur_state)

    for year in map_year_list:
        cur_year = cur_state + year + "/"
        map_file_list = os.listdir(cur_year)

        for file in map_file_list:
            cur_file = cur_year + file
            data = open(cur_file, 'r')
            C = json.load(data)

            for i in C["data"]["hoverDataList"]:
                district = i["name"]
                count = i["metric"][0]["count"]
                amount = i["metric"][0]["amount"]
                columns3["District"].append(district)
                columns3["Count"].append(count)
                columns3["Amount"].append(amount)
                columns3['State'].append(state)
                columns3['Year'].append(year)
                columns3['Quarter'].append(int(file.strip('.json')))

df_map_trans = pd.DataFrame(columns3)

In [ ]:
df_map_trans

            State  Year  Quarter             District     Count        Amount
0      chandigarh  2018        1  chandigarh district    381895  6.134354e+08
1      chandigarh  2018        2  chandigarh district    479084  9.612233e+08
2      chandigarh  2018        3  chandigarh district    616936  1.369354e+09
3      chandigarh  2018        4  chandigarh district    905116  2.032592e+09
4      chandigarh  2024        1  chandigarh district  13155173  1.584218e+10
...           ...   ...      ...                  ...       ...           ...
20599       delhi  2023        4    shahdara district  30001836  5.282506e+10
20600       delhi  2023        4  north east district  29422483  5.054895e+10
20601       delhi  2023        4        east district  43082162  5.088614e+10
20602       delhi  2023        4  north west district  49542115  7.462120e+10
20603       delhi  2023        4       north district  49234225  6.939050e+10

[20604 rows x 6 columns]

In [ ]:
path4 = "/content/pulse/data/map/user/hover/country/india/state/"

map_user_list = os.listdir(path4)

columns4 = {"State": [], "Year": [], "Quarter": [], "District": [],
            "RegisteredUser": [], "AppOpens": []}

for state in map_user_list:
    cur_state = path4 + state + "/"
    map_year_list = os.listdir(cur_state)

    for year in map_year_list:
        cur_year = cur_state + year + "/"
        map_file_list = os.listdir(cur_year)

        for file in map_file_list:
            cur_file = cur_year + file
            data = open(cur_file, 'r')
            D = json.load(data)

            for i in D["data"]["hoverData"].items():
                district = i[0]
                registereduser = i[1]["registeredUsers"]
                appOpens = i[1]['appOpens']
                columns4["District"].append(district)
                columns4["RegisteredUser"].append(registereduser)
                columns4["AppOpens"].append(appOpens)
                columns4['State'].append(state)
                columns4['Year'].append(year)
                columns4['Quarter'].append(int(file.strip('.json')))

df_map_user = pd.DataFrame(columns4)

In [ ]:
df_map_user

,State,Year,Quarter,District,RegisteredUser,AppOpens
0,chandigarh,2018,1,chandigarh district,86268,0
1,chandigarh,2018,2,chandigarh district,115219,0
2,chandigarh,2018,3,chandigarh district,143893,0
3,chandigarh,2018,4,chandigarh district,177747,0
4,chandigarh,2024,1,chandigarh district,754849,2680802
...,...,...,...,...,...,...
20603,delhi,2023,4,shahdara district,1124343,53424787
20604,delhi,2023,4,north east district,1014509,46191065
20605,delhi,2023,4,east district,1367614,50879134
20606,delhi,2023,4,north west district,1933267,83288102
20607,delhi,2023,4,north district,1583005,75047516

In [ ]:
path5 = "/content/pulse/data/top/transaction/country/india/state/"

top_trans_list = os.listdir(path5)
columns5 = {'State': [], 'Year': [], 'Quarter': [], 'Pincode': [], 'Transaction_count': [],
            'Transaction_amount': []}

for state in top_trans_list:
    cur_state = path5 + state + "/"
    top_year_list = os.listdir(cur_state)

    for year in top_year_list:
        cur_year = cur_state + year + "/"
        top_file_list = os.listdir(cur_year)

        for file in top_file_list:
            cur_file = cur_year + file
            data = open(cur_file, 'r')
            E = json.load(data)

            for i in E['data']['pincodes']:
                name = i['entityName']
                count = i['metric']['count']
                amount = i['metric']['amount']
                columns5['Pincode'].append(name)
                columns5['Transaction_count'].append(count)
                columns5['Transaction_amount'].append(amount)
                columns5['State'].append(state)
                columns5['Year'].append(year)
                columns5['Quarter'].append(int(file.strip('.json')))
df_top_trans = pd.DataFrame(columns5)

In [ ]:
df_top_trans

           State  Year  Quarter Pincode  Transaction_count  Transaction_amount
0     chandigarh  2018        1  160008             204745        3.034820e+08
1     chandigarh  2018        1  160101              26317        4.562948e+07
2     chandigarh  2018        1  160002              23236        3.400308e+07
3     chandigarh  2018        1  160036              18446        3.089135e+07
4     chandigarh  2018        1  160022              16228        3.402815e+07
...          ...   ...      ...     ...                ...                 ...
9994       delhi  2023        4  110096           15205954        1.705516e+10
9995       delhi  2023        4  110086           13539030        2.086114e+10
9996       delhi  2023        4  110053           13467866        2.509407e+10
9997       delhi  2023        4  110041           13458704        2.058779e+10
9998       delhi  2023        4  110037           13170706        1.435283e+10

[9999 rows x 6 columns]

In [ ]:
path6 ="/content/pulse/data/top/user/country/india/state/"
top_user_list = os.listdir(path6)
columns6 = {'State': [], 'Year': [], 'Quarter': [], 'Pincode': [],
            'RegisteredUsers': []}

for state in top_user_list:
    cur_state = path6 + state + "/"
    top_year_list = os.listdir(cur_state)

    for year in top_year_list:
        cur_year = cur_state + year + "/"
        top_file_list = os.listdir(cur_year)

        for file in top_file_list:
            cur_file = cur_year + file
            data = open(cur_file, 'r')
            F = json.load(data)

            for i in F['data']['pincodes']:
                name = i['name']
                registeredUsers = i['registeredUsers']
                columns6['Pincode'].append(name)
                columns6['RegisteredUsers'].append(registeredUsers)
                columns6['State'].append(state)
                columns6['Year'].append(year)
                columns6['Quarter'].append(int(file.strip('.json')))
df_top_user = pd.DataFrame(columns6)

In [ ]:
df_top_user

           State  Year  Quarter Pincode  RegisteredUsers
0     chandigarh  2018        1  160101            11805
1     chandigarh  2018        1  160002            10228
2     chandigarh  2018        1  160036             9118
3     chandigarh  2018        1  160047             8701
4     chandigarh  2018        1  160022             7205
...          ...   ...      ...     ...              ...
9995       delhi  2023        4  110094           444837
9996       delhi  2023        4  110085           442488
9997       delhi  2023        4  110053           438988
9998       delhi  2023        4  110096           430061
9999       delhi  2023        4  110042           428202

[10000 rows x 5 columns]

In [ ]:
df_agg_trans.to_csv('agg_trans.csv',index=False)
df_agg_user.to_csv('agg_user.csv',index=False)
df_map_trans.to_csv('map_trans.csv',index=False)
df_map_user.to_csv('map_user.csv',index=False)
df_top_trans.to_csv('top_trans.csv',index=False)
df_top_user.to_csv('top_user.csv',index=False)